version: '3'
services:
  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:14.5-alpine
    ports:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
volumes:
  postgres:
  bundler_gems:
  node_modules:
  pgadmin_data: