name: Verify
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run linters
        run: |
          bundle exec rubocop

  tests:
    name: Tests
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      RAILS_ENV: ${{ secrets.RAILS_ENV }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    runs-on: ubuntu-latest
    environment: development
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports: [ "5432:5432" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup CodeClimate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Setup environment
        run: |
          bundle exec rails db:setup
          bundle exec rails tailwindcss:install

      - name: Run rSpec
        run: |
          bundle exec rspec
          ./cc-test-reporter after-build
        
